### ISSUE TITLE
Looks ugly with fresh Atom 1.0

### ISSUE THREAD

**Issue by eldargab** [oggy/tab-switcher#12]
Hi, I just installed Atom and tab-switcher and got this out of the box

![image](https://cloud.githubusercontent.com/assets/762157/8381492/a9592e74-1c34-11e5-8d8d-c6e91e6151b9.png)

**Comment by Trcx528** [comment]
![screenshot from 2015-06-27 00 24 27](https://cloud.githubusercontent.com/assets/1213427/8390604/ec287204-1c62-11e5-88a9-909def2fd348.png)

I too am experiencing some weirdness with the switcher window.  It appears shorter than expected and has strange lines extending from the top and the bottom across the width of the screen.  I assume is unintended behavior as it does not appear to act like this in the demo gif.

**Comment by calvinchoy** [comment]
You can temporary fix this by adding this to your own styles.less:

```css
ol.tab-switcher-tab-list{
    overflow:hidden;
}
```

The problem is probably caused by the default `overflow:scroll`

**Comment by eldargab** [comment]
@calvinchoy looks better, but still weird

**Comment by oggy** [comment]
@eldargab @Trcx528 Thanks for the feedback! Just pushed an update that will hopefully fix these issues.

**Comment by Trcx528** [comment]
Much better, thank you for the quick fix!
