### ISSUE TITLE
Tabs list remains visible after closing last tab

### ISSUE THREAD

**Issue by jutky** [oggy/tab-switcher#17]
Hello,
First of all, thanks a lot for a useful package.

Second, there is strange behavior in the following scenario.
If I switch to another tab and then I close the currently active tab, I'm returned the my previous tab.
But the tab switching dialog is still displayed there!
I think it should be hidden in such a case.

Thanks again.

**Comment by oggy** [comment]
Thanks for reporting! Will publish the fix shortly.
