### ISSUE TITLE
When switching fast, avoid the black flash?

### ISSUE THREAD

**Issue by jeanlauliac** [oggy/tab-switcher#20]
When quicking switching to the previous file, we don't need the history list to display. The problem is that the menu displays immediately, so when switching fast there's am annoying black flash happening. To fix this, we could simply have a little delay between the key-press and the menu appearing.

This is the same behavior as Meta-Tab in OS X or Windows, where you have a little delay before the menu appears, for this very reason.

**Comment by oggy** [comment]
Thanks for the suggestion!

I just pushed v1.3.0 which has a configurable option for this (defaults to a 0.1s delay).
