### ISSUE TITLE
Skipping two files at once

### ISSUE THREAD

**Issue by leijou** [oggy/tab-switcher#22]
1.3.1 introduced a bug for me where each `alt-]` call moves forward two tabs in the list instead of one, and the same backwards for `alt-[`. This happened both with and without custom keybindings. Installing version 1.3.0 again clears the issue.

**Comment by leijou** [comment]
Sorry, false alarm. Upgrading to 1.3.1 again fixed the issue. Must have been something double-registering during the update.

**Comment by Getz85** [comment]
Same problem here after upgrading to 1.3.2. Works well after an Atom restart.
