### ISSUE TITLE
File list highlights entry under stationary mouse when highlighted entry is in lower half of screen 

### ISSUE THREAD

**Issue by Tyriar** [oggy/tab-switcher#28]
Given a sufficiently large list of open files, using `tab-switcher:next` or `tab-switcher:previous` will highlight the entry under the mouse (that has not moved) when the highlighted file goes to the bottom half of the screen.

![out](https://cloud.githubusercontent.com/assets/2193314/10736124/8b8ce842-7bc8-11e5-82e8-8cd4145886b2.gif)

**Comment by oggy** [comment]
Sorry for the wait -- fixed in 1.3.3. Thanks!

**Comment by Tyriar** [comment]
:+1:
