### ISSUE TITLE
BUG: titled displayed is outdated

### ISSUE THREAD

**Issue by mzbik** [oggy/tab-switcher#29]
Atom 1.1.0

1. Create new file. It's called Untitled. 
2. Save file. Prompted to save and enter Foo
3. File is saved. Tab renamed to Foo
4. Call up tab-switcher. 
     * BUG: File shows up as Untitled, expected is Foo

Possible dup of #26

**Comment by oggy** [comment]
Confirmed as dupe of #26, which is fixed.
