### ISSUE TITLE
Directories Missing

### ISSUE THREAD

**Issue by littlebee** [oggy/tab-switcher#31]
Help please.  It was working, I think maybe before I upgraded atom to 1.2.3?    
OSX 10.10.5  Gist of my current setup: https://gist.github.com/littlebee/34a60734de79f6f78c56

<img width="762" alt="settings_-__users_bwilkerson_projects_zulily_react-datum_-_atom" src="https://cloud.githubusercontent.com/assets/593784/11461552/185d3450-96ba-11e5-8e76-ff79bf3fa67e.png">

**Comment by oggy** [comment]
Fixed in 1.3.3. Thanks!

**Comment by littlebee** [comment]
It works again!   Thank you!!!  love this addon
