### ISSUE TITLE
Simple configuration.

### ISSUE THREAD

**Issue by jordwalke** [oggy/tab-switcher#36]
I was trying to achieve a very simple configuration of this plugin but I don't know if it's supported yet. I want to use this as a very simple "go to last tab". There's a couple of issues.

- I don't ever want the tab list dialog to pop up. I typically just want to hit a keyboard combination and have it go to the last tab. I could set the delay to a high amount but see the next issue:
- Tab switching (going to last tab) should occur on key *down* just like other tab switching shortcuts in `Atom` (or anything else).

**Comment by oggy** [comment]
I think the default in Atom 1.7 is just what you're after.
