### ISSUE TITLE
Tab switcher not working with Atom 1.7

### ISSUE THREAD

**Issue by davidhazeland** [oggy/tab-switcher#37]
The tab list not disappearing when releasing alt key.

**Comment by oggy** [comment]
Thanks for the report!

I've pushed an attempt to fix this to the `atom-17` branch. Will merge it in soon hopefully -- I'd just like to try it out for a bit first.

**Comment by FlorianBezagu** [comment]
Hi,

I tried your `atom-17` branch but it does not work with my keybindings. I try to use `ctrl-tab` and `ctrl-shift-tab` keybindings. When I release keys it does not select the hovered tab.

I changed my keybindings following what you did in your commit. It look likes :

```
  'shift-ctrl-tab': 'tab-switcher:previous'
  'ctrl-tab': 'tab-switcher:next'
  'ctrl-tab ^ctrl': 'tab-switcher:select'
  'ctrl-shift-tab ^ctrl': 'tab-switcher:select'
```

Can you help me by providing an example on how to use it correctly please ?

Thanks.

**Comment by FlorianBezagu** [comment]
It works ! 😄 

I'am on your `atom-17` branch and my `keymap.cson` looks like :

```
'atom-workspace':
  'ctrl-tab' : 'tab-switcher:next'
  'ctrl-tab ^ctrl' : 'unset!'
  'ctrl-shift-tab' : 'tab-switcher:previous'
  'ctrl-shift-tab ^ctrl' : 'unset!'
'ol.tab-switcher-tab-list':
  '^ctrl' : 'tab-switcher:select'
```

**Comment by GerZah** [comment]
… Hhhm … Doesn't work for me …

However: The main reason why I actually installed tab-switcher was to have a working MRU on my Ctrl-Tab / Ctrl-Shift-Tab window switching. After being forced to disable tab-switcher and to comment out its key bindings, I just realized that Atom 1.7.2 seems to have implemented window tabbing MRU itself – which makes tab-switcher obsolete for me.

**Comment by FlorianBezagu** [comment]
@GerZah Yes I know but I don't like this new MRU feature.

I want, just like other good IDEs a window to switch to more than my previous tab. That's why I love `tab-switcher` and it worked great before Atom 1.7.

PS : I'm on `OSX 10.11.5` / Atom `1.7.2`

**Comment by oggy** [comment]
Glad you were able to figure out the key bindings @FlorianBezagu . In the spirit of a couple of PRs, I've added some notes based on your suggestion to the readme.

Pushed as v1.4.0.

**Comment by FlorianBezagu** [comment]
Great !

Thanks for your work. 👍
