### ISSUE TITLE
Stopped working in Atom 1.7.2

### ISSUE THREAD

**Issue by matixmatix** [oggy/tab-switcher#38]
When I hit CTRL+TAB and it opens tab list, the tab list does not close itself and activate selected file after I release CTRL+TAB, as it used to do. 

Atom: 1.7.2
Tab Switcher: 1.4.0

**Comment by oggy** [comment]
Hmm, if I use the instructions in the README, it worked for me, except I noticed the list didn't go away if I released ctrl before shift. [This latest change](https://github.com/oggy/tab-switcher/commit/b28d4a27c4b5ac81c5fbf690e77fc8ea594dd7dd) fixes that.

If this still doesn't work for you, please reopen and include your `keymap.cson`.

**Comment by matixmatix** [comment]
This solved it. Thanks @oggy ! I ❤️ Tab Switcher.
