### ISSUE TITLE
Crtl-tab

### ISSUE THREAD

**Issue by utiq** [oggy/tab-switcher#40]
Hi, with the previous version of this awesome plugin I used to work very nice with the functionality of switch tabs with crtl-tab.
I don't know if is this last update but now every time I do it, it doesn't change. I added this to disable the new 1.7 Atom tabs functionality:

'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
  'ctrl-shift-tab ^ctrl': 'unset!'

and this is my custom configuration:

'atom-workspace':
  'ctrl-tab': 'tab-switcher:next'
  'ctrl-shift-tab': 'tab-switcher:previous'

OS: El Capitan
Atom: 1.7.2

**Comment by oggy** [comment]
Please see the readme -- there are a few other bindings needed to make everything work with Atom 1.7.
