### ISSUE TITLE
Option to disable mouse hover altering the selection

### ISSUE THREAD

**Issue by pknowles** [oggy/tab-switcher#41]
I frequently find my mouse is moving as I'm switching tabs. I hit the shortcut so quickly I don't even see the mouse has selected something else and just find myself viewing a random file. It'd be great to be able to disable this. Interaction with the mouse is still useful, such as being able to click on (not just hover over) a file when it's in the middle of the list and I can't be bothered spamming the shortcut.

**Comment by cakraww** [comment]
I second that. It's a bit annoying to have the mouse hover destroy the experience of tab switching.

**Comment by oggy** [comment]
I've found this to be a problem too, but I believe the problem was a buggy implementation, so I've tried to fix this rather than add an option to disable it. I'll push a new release shortly.

Thanks for the report!
