### ISSUE TITLE
Wrong tab order on first try

### ISSUE THREAD

**Issue by keskiju** [oggy/tab-switcher#44]
It seems that tab-switcher activates only after user executes "tab-switcher:next" or "tab-switcher:previous" the first time. And only after activation tab-switcher starts to track the tab activation order. Therefore the first time you use tab-switcher after starting atom, it does not open the previous/next tab that you had active.

**Comment by kataho** [comment]
It can be fixed by removing activationComands entry from package.json.
Probably there is any reason to choose this lazy loading behavior, I have no idea.

**Comment by oggy** [comment]
The only reason is to try to be a "good citizen" and not add to the editor's startup time.

The package takes < 20ms to load for me, though and the only alternatives I can think of have shortcomings, so I'm going to merge @keskiju's PR.

Thanks for the contributions!
