### ISSUE TITLE
Switch window is offscreen

### ISSUE THREAD

**Issue by GillesDebunne** [oggy/tab-switcher#49]
Since the update to Atom 1.8.0, the tab switcher window appears in the top left corner instead of being centered on screen. With long file and path names, it is clipped, making it barely usable.

![tab-switcher](https://cloud.githubusercontent.com/assets/1897114/16177277/d67b3bc8-3627-11e6-868c-5a2d1816d846.jpg)

This is using Mac OSX 10.11.5, tab-switcher 1.5.1 and Atom 1.8.0. I tried uninstalling / reinstalling the package, but with no success.

Thanks,

G

**Comment by oggy** [comment]
Funny, I just noticed that myself yesterday. Just pushed a release which should fix this.

Thanks for the report!

**Comment by GillesDebunne** [comment]
Thanks for this quick fix.

However, the fix seems to have introduced a new problem. When I open the `fuzzy-finder:toggle-file-finder` (Cmd+T), the search window is now shifted down, partially invisible.

Disabling the `tab-switcher` package fixes the problem.

G

**Comment by sirianni** [comment]
In my case, all atom modals are at the bottom of the window.  Disabling the `position: static` rule on `atom-panel-container` seems to fix it.  Strangely, the rule is being applied even though the `tab-switcher` class is not present on the element.

**Comment by sirianni** [comment]
Actually, the problem seems to be that the other modal (in my case "fuzzy finder") is nested within a tab-switcher modal:

```html
<atom-panel-container class="modal tab-switcher">
    <atom-panel class="tab-switcher modal overlay from-top" style="display: none; transition-delay: 0.1s;">
        <div class="vertical-axis">
            <ol class="tab-switcher-tab-list" tabindex="-1">
                <li data-id="5"><span class="icon icon-tools"></span><span class="tab-label">Settings</span></li>
            </ol>
        </div>
    </atom-panel>
    <atom-panel class="modal overlay from-top">
        <div class="select-list fuzzy-finder" is="space-pen-div">
        </div>
    </atom-panel>
</atom-panel-container>
```

**Comment by oggy** [comment]
@GillesDebunne @sirianni 

Dangit, sorry about that. Looks like the pane-container is shared with other panels.

I guess I should stop using panels for this, since themes seem to take liberty with panel positioning, and the tab list is kind of a separate thing. I'm short on time though, so I've just hacked the hack for now.

**Comment by sirianni** [comment]
Looks like it's fixed - I just upgraded this morning.  Thanks for the quick turnaround!
