### ISSUE TITLE
Releasing Ctrl-Tab does not switch the tab.

### ISSUE THREAD

**Issue by ChrisCinelli** [oggy/tab-switcher#51]
A mouse action is necessary to close the tab switcher overlay

![problem-with-tab-switcher-](https://cloud.githubusercontent.com/assets/153101/16288307/43f53004-389f-11e6-913d-300ee47ec751.gif)

**Comment by oggy** [comment]
Hi @ChrisCinelli -- what version of Atom are you using? And if it's not 1.8.0, does upgrading help?

If you're on 1.8, please provide: OS & version, and other packages & versions you have installed. FWIW I haven't seen this behavior in my testing (mac, windows, linux).

**Comment by ChrisCinelli** [comment]
I have 1.8.

These are my packages (all updated to the latest): 

```
$  ~/.atom/packages/
atom-ternjs/                git-plus/                   minimap/
autocomplete-html-entities/ git-tabs/                   open-github-from-npm/
autocomplete-modules/       hyperclick/                 pigments/
autocomplete-paths/         hyperclick-php/             react/
emmet/                      js-hyperclick/              rename-tabs/
file-icons/                 linter/                     tab-switcher/
fixmyjs/                    linter-codeclimate/
git-blame/                  linter-jscs/
```

**Comment by andrejkosyak** [comment]
I've got the same bug.
Version 1.8

```
~/.atom/packages|
⇒  ls
README.md                   atom-ternjs/                git-plus/                   htmlhint/                   markdown-scroll-sync/       terminal-plus/
atom-beautify/              color-picker/               git-time-machine/           linter/                     minimap/
atom-material-syntax-light/ file-icons/                 highlight-line/             linter-csslint/             pigments/
atom-material-ui/           filesize/                   highlight-selected/         linter-htmlhint/            tab-switcher/
```

**Comment by ChrisCinelli** [comment]
I have some updates.

I just installed `tab-switcher` on a new machine. The default `Alt-[` and `Alt-]` work. What is not working is if I redefine them.

I have : 
```
'atom-workspace':
  'ctrl-tab': 'tab-switcher:next'
  'ctrl-shift-tab': 'tab-switcher:previous'
```

And when I release `Ctrl-Tab`, it does not select the tab.

**Comment by oggy** [comment]
Ok, thanks for the update @ChrisCinelli . I'm sorry I hadn't gotten around to investigating this.

Note the readme has a few extra bindings to make the other tab-switcher commands work if you're customizing the modifier.
