### ISSUE TITLE
Is It possible to user another file icon package?

### ISSUE THREAD

**Issue by tchesa** [oggy/tab-switcher#52]
I am user this icon package (https://atom.io/packages/atom-icons) and I want to show these icons on tab switcher instead of the recommended icon package. Is It easy to do in tab-switcher's source code?

**Comment by oggy** [comment]
Probably. The existing icons work by applying [these css classes](https://github.com/oggy/tab-switcher/blob/57ccf135d72a383adcf24ee7105f44906506a624/lib/tab-list-view.coffee#L167) (and `icon-tools` further down for settings). That other package might be quite similar.

**Comment by oggy** [comment]
Closing, as there's nothing to do here.

With the current file-icons integration, any alternative icons package may be used if it [implements a compatible service interface](http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/).
