### ISSUE TITLE
Can't actually switch to a tab

### ISSUE THREAD

**Issue by justus-alex** [oggy/tab-switcher#58]
After updating Atom (1.4.0 -> 1.12.7) and tab-switcher (1.3.3 -> 1.5.4).
I can invoke the pop-up list with the Ctrl-[Shift-]-Tab combination and move around with it (and only with it, not with arrow keys.. don't remember if they should work) but can't actually switch to the selected page with keyboard, nor by releasing the Ctrl key nor by pressing Enter. Mouse click works. Without mouse using the pop-up just gets stuck and disappears only after window switching (e.g. Alt-Tab) or pressing of another Atom key combination, like Ctrl-P or Ctrl-Shift-P etc. But in the last case there is an oddness too: the invoked window doesn't get focus, I can't input anything, Escape doesn't close it as well. But subsequent Atom command invocation works well.
So, the steps:
1. Open Atom and at least one (any) tab
2. Press Ctrl-[Shift-]-Tab
3. Release the Ctrl key, or press Enter. Ensure nothing happens.
4. Press Ctrl-P. Ensure the input is unfocused, Escape doesn't work. (You can focus the input with mouse click, actually).
5. Press Ctrl-Shift-P. All works well.

Ubuntu 14.04
Linux 3.13.0-96-generic
Atom 1.12.7
tab-switcher 1.5.4

Installed atom packages (not all of them are enabled):
atom-beautify@0.29.13
close-tags@0.6.0
ctrl-last-tab@0.3.0
docblockr@0.9.1
double-click-tree-view@1.1.0
git-control@0.8.2
git-log@0.4.1
git-plus@5.29.0
git-time-machine@1.5.4
goto@1.8.2
goto-definition@1.1.19
jumpy@3.1.3
minimap@4.25.7
project-view@0.6.1
react@0.16.1
switch-tab@0.1.0
symbol-gen@1.3.1
symbols-tree-view@0.13.2
tab-switcher@1.5.4
tasks@2.6.4
tree-view-git-status@1.3.0
zentabs@0.8.7

**Comment by juan-lb** [comment]
I think that the problem is the "ALT" key. I had to change my keybinding, with "CTRL-{" I get the same problem, but if use "ALT-{", everything is fine.

**Comment by oggy** [comment]
I'm unable to repro this using latest versions of Atom & tab-switcher on linux (Ubuntu 16.10), so I'm going to assume this is a stale issue. Reopen if you find otherwise.

Note that to use a different modifier, the set of bindings to use has changed a little. See the readme for a current example.
