### ISSUE TITLE
Using hotkey pollutes current file with extraneous character

### ISSUE THREAD

**Issue by Overload119** [oggy/tab-switcher#61]
When using the `alt+]` hotkeys, the file that is currently selected will get polluted with the following character: `‘` It seems to me it's because the hotkey is not being captured?

**Comment by oggy** [comment]
Thanks for the report Amir. I noticed this too and traced it down to a bug in a core package (atom/atom-keymap#205) a while ago. Unfortunately I haven't seen much activity in a while on this issue.

As a workaround, I believe using a different binding that doesn't involve alt should work. The readme includes an example of how to do this.
