### ISSUE TITLE
Plugin is not working well on newest version of Atom after introducing Docks

### ISSUE THREAD

**Issue by scsmash3r** [oggy/tab-switcher#62]
Plugin doesn't work well with the newest Atom version because of new panels (docks): http://blog.atom.io/2017/05/16/atom-1-17.html

Moreover, it overlaps keymaps with core ones, so using ctrl+tab shortcut opens right pane instead.

Current behaviour: when you try to use tab switcher, black overlay with opacity appears and nothing more. After releasing tab, Atom's right dock appears (collision with ` 'ctrl-tab': 'pane:show-next-recently-used-item'` - and you can't really rewrite that...)

**Comment by utiq** [comment]
Same issue for me, could you solve it?

**Comment by zarathosss** [comment]
Same issue here.
